[package]
name = "hot_reload"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "6.1"
clap = { version = "4", features = ["derive"] }
which = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
